// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQWk_XB2epPUE4xRWZcTK3qvaOMams_Fc',
    appId: '1:298750031686:web:6066a251603792d0de5747',
    messagingSenderId: '298750031686',
    projectId: 'kidsapp-3c912',
    authDomain: 'kidsapp-3c912.firebaseapp.com',
    storageBucket: 'kidsapp-3c912.appspot.com',
    measurementId: 'G-DBJ070TJ32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABHrzuqXXqymS56b1fwLlGE3psud_isHQ',
    appId: '1:298750031686:android:3cc5e07929f46e93de5747',
    messagingSenderId: '298750031686',
    projectId: 'kidsapp-3c912',
    storageBucket: 'kidsapp-3c912.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6o5LpmsUIO-R2Ki5tZwHvbWv-fOgApJE',
    appId: '1:298750031686:ios:132ffd0ee5eb51e3de5747',
    messagingSenderId: '298750031686',
    projectId: 'kidsapp-3c912',
    storageBucket: 'kidsapp-3c912.appspot.com',
    iosClientId: '298750031686-rhm2re39pmr855001i1slfmu3bhdlkft.apps.googleusercontent.com',
    iosBundleId: 'com.example.kidsappAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6o5LpmsUIO-R2Ki5tZwHvbWv-fOgApJE',
    appId: '1:298750031686:ios:132ffd0ee5eb51e3de5747',
    messagingSenderId: '298750031686',
    projectId: 'kidsapp-3c912',
    storageBucket: 'kidsapp-3c912.appspot.com',
    iosClientId: '298750031686-rhm2re39pmr855001i1slfmu3bhdlkft.apps.googleusercontent.com',
    iosBundleId: 'com.example.kidsappAdmin',
  );
}
